// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABTbjnJ9alNsKdqQWrWFRoBVEV0Kw1HbE',
    appId: '1:268048869259:web:70906c50beea54dabe318e',
    messagingSenderId: '268048869259',
    projectId: 'echoes-of-expanse',
    authDomain: 'echoes-of-expanse.firebaseapp.com',
    storageBucket: 'echoes-of-expanse.appspot.com',
    measurementId: 'G-7S1CWFD3QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJaGkzXPBWDgZ2eMFGUlxPDiWdBObcGo',
    appId: '1:268048869259:android:a3e01ce642e2d4d9be318e',
    messagingSenderId: '268048869259',
    projectId: 'echoes-of-expanse',
    storageBucket: 'echoes-of-expanse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkehSNhFqGgOmq9RUvHxmCbZtIClls0KE',
    appId: '1:268048869259:ios:8d8c105bafe452dfbe318e',
    messagingSenderId: '268048869259',
    projectId: 'echoes-of-expanse',
    storageBucket: 'echoes-of-expanse.appspot.com',
    iosBundleId: 'com.example.echoesOfExpanse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkehSNhFqGgOmq9RUvHxmCbZtIClls0KE',
    appId: '1:268048869259:ios:f3bd899f9017a4e0be318e',
    messagingSenderId: '268048869259',
    projectId: 'echoes-of-expanse',
    storageBucket: 'echoes-of-expanse.appspot.com',
    iosBundleId: 'com.example.echoesOfExpanse.RunnerTests',
  );
}
